export const actionTypes = {
  //authenticaation action types
  ON_LOGIN: "ON_LOGIN",
  // COMPANY
  ADD_COMPANY: "ADD_COMPANY",
  GET_COMPANIES: "GET_COMPANIES",
  GET_COMPANY: "GET_COMPANY",
  UPDATE_COMPANY: "UPDATE_COMPANY",
  DELETE_COMPANY:" DELETE_COMPANY",
  // PARTNER
  ADD_PARTNER: "ADD_PARTNER",
  GET_PARTNERS: "GET_PARTNERS",
  GET_PARTNER: "GET_PARTNER",
  UPDATE_PARTNER: "UPDATE_PARTNER",
  DELETE_PARTNER:" DELETE_PARTNER",
   // PROJECT
   ADD_PROJECT: "ADD_PROJECT",
   GET_PROJECTS: "GET_PROJECTS",
   GET_PROJECT: "GET_PROJECT",
   UPDATE_PROJECT: "UPDATE_PROJECT",
   // EMPLOYEE
   ADD_EMPLOYEE: "ADD_EMPLOYEE",
   GET_EMPLOYEES: "GET_EMPLOYEES",
   GET_EMPLOYEE: "GET_EMPLOYEE",
   UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
   // VENDOR
   ADD_VENDOR: "ADD_VENDOR",
   GET_VENDORS: "GET_VENDORS",
   GET_VENDOR: "GET_VENDOR",
   UPDATE_VENDOR: "UPDATE_VENDOR",
};
