export const actionTypes = {
  //authenticaation action types
  ON_LOGIN: "ON_LOGIN",
  ADD_COMPANY: "ADD_COMPANY",
  GET_COMPANIES: "GET_COMPANIES",
  GET_COMPANY: "GET_COMPANY",
  UPDATE_COMPANY: "UPDATE_COMPANY",
  PARTNERS: "PARTNERS",
  VENDOR_LIST: "VENDOR_LIST",
};
